/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwardList: typeof import('./src/components/editor/AwardList.vue')['default']
    BoldTextarea: typeof import('./src/components/editor/BoldTextarea.vue')['default']
    ContentEditor: typeof import('./src/components/sidebar/ContentEditor.vue')['default']
    DesignEditor: typeof import('./src/components/sidebar/DesignEditor.vue')['default']
    EducationList: typeof import('./src/components/editor/EducationList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExperienceList: typeof import('./src/components/editor/ExperienceList.vue')['default']
    ListItemBase: typeof import('./src/components/shared/ListItemBase.vue')['default']
    MeasureContainer: typeof import('./src/components/preview/MeasureContainer.vue')['default']
    PageRenderer: typeof import('./src/components/preview/PageRenderer.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    PrintContainer: typeof import('./src/components/preview/PrintContainer.vue')['default']
    ProjectList: typeof import('./src/components/editor/ProjectList.vue')['default']
    ResumeContent: typeof import('./src/components/ResumeContent.vue')['default']
    SelfEvaluationEditor: typeof import('./src/components/editor/SelfEvaluationEditor.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarFooter: typeof import('./src/components/sidebar/SidebarFooter.vue')['default']
    SidebarHeader: typeof import('./src/components/sidebar/SidebarHeader.vue')['default']
    SidebarTabs: typeof import('./src/components/sidebar/SidebarTabs.vue')['default']
    SidebarToggle: typeof import('./src/components/sidebar/SidebarToggle.vue')['default']
    SponsorButton: typeof import('./src/components/SponsorButton.vue')['default']
  }
}
